services:
  interhealth-api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${APP_PORT}:${APP_PORT}"
        
    environment:
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: ${MONGO_URL}
      
    restart: unless-stopped
